### PR TITLE
Switch to version 3.9.0 of the openwhisk SDK

### PR DESCRIPTION
**Pull request by gbdrt**

### CODE REVIEW

**Comment by rabbah** [comment]
@csantanapr are you ok with this change?

**Comment by csantanapr** [comment]
There is no good thing of using .x more work to figure out what version actually got installed on the image and then update the docs. 
It will make it a mess start guessing what version ended in what tag

**Comment by csantanapr** [comment]
It's not like the library is going to be installed and be updated any time the client lib is release, the npm happens at image creation not at the time action init happens

**Comment by gbdrt** [comment]
Ok, just changed it back.

**Comment by jthomas** [comment]
Is there a way to automate the process of opening a PR each time the openwhisk client lib changes?

**Comment by csantanapr** [comment]
Yeah we can look into it. 
First I would implement a deploy step in Travis, then from the deploy scripts open a PR against this repo.

**Comment by gbdrt** [comment]
I don't know why the build failed.
The last travis output is:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
@csantanapr did I missed something?
`npm install` was successful with v.3.9.0 of the open whisk SDK, which is the only change  I made.

**Comment by csantanapr** [comment]
@gbdrt 
Don't know what's going on with Travis and docker build.
I restarted the build and it worked.

Now that I created a tag for the image and trying to build it, it also get's stuck already restarted multiple times
https://travis-ci.org/apache/incubator-openwhisk-runtime-nodejs/builds/292315194

**Pull request merged**
